### ISSUE TITLE
Reliance on Bulma version

### ISSUE THREAD

**Issue by dhruvbhatia** [Marciola/phoenix-bulma#1]
Great project / tutorial! Is there a way to bring in Bulma via the `node_modules` dependancy, rather than explicitly having to download a specific version? Would love if it could be auto-updating.

**Comment by dhruvbhatia** [comment]
NVM, figured out you can simply add `@import '../node_modules/bulma/bulma.sass';` to your `assets/css/app.scss` file which will bring in the version defined in your `assets/package.json` file!

**Comment by Marciola** [comment]
Thanks for letting me know! I'll add that to the documentation as I'm sure there will be others looking for this.
